<?php

namespace P2\Bundle\OfferBundle\Entity\Repository;

/**
 * CreditCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreditCardRepository extends \Doctrine\ORM\EntityRepository
{
}
