<?php

namespace P2\Bundle\OfferBundle\Entity\Repository;

/**
 * OfferItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferItemRepository extends \Doctrine\ORM\EntityRepository
{
}
