<?php

namespace P2\Bundle\ProductBundle\Entity\Repository;

/**
 * ProductLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductLineRepository extends \Doctrine\ORM\EntityRepository
{
}
