<?php

namespace P2\Bundle\UserBundle\Entity\Repository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAddressessWithThis($term)
	{	
		$em = $this->getEntityManager();
		//FIXME dql needs to be improved, the LIKE option isn't working properly
		$dql = "SELECT a
				FROM P2UserBundle:Address a
				WHERE a.search LIKE :term
				ORDER BY a.street ASC";

		$query = $em->createQuery($dql);

		$query->setParameters(array('term' => '%'.$term.'%'));

		return $query->getResult();
	}
}
