<?php

namespace P2\Bundle\UserBundle\Entity\Repository;

/**
 * DeliveryManRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryManRepository extends \Doctrine\ORM\EntityRepository
{
}
