<?php

namespace P2\Bundle\UserBundle\Entity\Repository;

/**
 * ProductManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductManagerRepository extends \Doctrine\ORM\EntityRepository
{
}
