<?php

namespace P2\Bundle\UserBundle\Entity\Repository;

/**
 * SellerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SellerRepository extends \Doctrine\ORM\EntityRepository
{
}
